### ISSUE TITLE
Simplify C code generation backend and remove experimental/unnecessary options

### ISSUE THREAD

**Issue by pramodk** [BlueBrain/nmodl#850]
While trying to redo code generation for `nrn_cur` and `nrn_state` in the LLVM branch, I notice that there are old/experimental options in the C backend that could be just removed at this stage. They will be useful `at some point in the future` but the current coreneuron setup doesn't allow us to use them anyway. So they are just making 🍝 now!

List of such options/flags (WIP)

- [x] Remove OpenMP backend ? #858 
- [x] channel_task_dependency_enabled #858 
- [x] print_channel_iteration_tiling_block_begin and print_channel_iteration_block_end #963 
- [x] Not sure if declarations using `k_const()` is really useful #882
- [x] Same situation with `ptr_type_qualifier()` #965 
- [x] Unused CUDA backend #962 
- [x] Unused ISPC backend #963 

The idea here is to make a list of all such cleanup and simplify the C visitor. This will make things cleaner, easy to understand and implement the code generation for NEURON easier.

**Comment by alkino** [comment]
Everything has been removed. Let's close?
